export enum AUTH_ACTIONS_TYPES {
  LOGIN = 'LOGIN',
  USER_LOGGED = 'USER_LOGGED',
  CHECK_LOGGED = 'CHECK_LOGGED',
  USER_CHECKED = 'USER_CHECKED',
  SET_LOGIN_ERROR = 'SET_LOGIN_ERROR',
  SIGN_UP = 'SIGN_UP',
}
