export enum POKEMONS_ACTIONS_TYPES {
  GET_POKEMON_LIST = 'GET_POKEMON_LIST',
  LIST_POKEMON_LOADED = 'LIST_POKEMON_LOADED',
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
  SET_POKEMON_NAME = 'SET_POKEMON_NAME',
  GET_POKEMON_BY_NAME = 'GET_POKEMON_BY_NAME',
  CURRENT_POKEMON_LOADED = 'CURRENT_POKEMON_LOADED',
}
